### ISSUE TITLE
expect a detailed document or tutorial

### ISSUE THREAD

**Issue by andyyuan78** [trademob/anna-molly#25]

**Comment by Puneeth-n** [comment]
Hi @andyyuan78,

Steps to configure Anna-Molly are provided in [this] (https://github.com/trademob/anna-molly#configuration "Configuration") section of [README] (https://github.com/trademob/anna-molly/blob/master/README.md)

Details of the various algorithms that are currently available in Anna-Molly are present in the [wiki] (https://github.com/trademob/anna-molly/wiki "Anna-Molly Wiki").

Furthermore, We also have a [gitter room](https://gitter.im/trademob/anna-molly) where we can chat about the project and answer further queries.
